#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)

while IFS=$'\t' read -r dest src; do
  dest="$REPO_ROOT/$dest"
  if [[ -d "$src" ]]; then
    rm -rf "$dest"
    cp -r "$src" "$dest"
  else
    cp "$src" "$dest"
  fi
  git add "$dest"
done < "$REPO_ROOT/symlinks"
