#!/bin/bash
# Runs a command with a braille spinner; prints "ok" on success or error output on failure.

source $HOME/.config/shell/aliases.sh

shopt -s expand_aliases

frames=("⠋" "⠙" "⠹" "⠸" "⠼" "⠴" "⠦" "⠧" "⠇" "⠏")

output=$(mktemp)

eval "$@" >"$output" 2>&1 &
pid=$!

# Hide cursor
tput civis

i=0
while kill -0 "$pid" 2>/dev/null; do
  printf "\r${frames[i]} " # carriage return
  i=$(((i + 1) % ${#frames[@]}))
  sleep 0.08
done

# Show cursor again
tput cnorm

wait "$pid"
exit_code=$?

if [ $exit_code -eq 0 ]; then
  printf "\r\033[32mok\033[0m\n"
else
  printf "\r\033[31merror\033[0m\n\n"
  cat "$output"
fi

rm "$output"

exit $exit_code
